name: droidenv
channels:
  - rusty1s
  - pytorch
  - open3d-admin
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-scatter
  - torchaudio
  - torchvision
  - open3d
  - pytorch=1.9.0
  - cudatoolkit=11.1
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
